spring:
  application:
    name: resource-server

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  batch:
    job:
      enabled: false
    sql:
      init:
        mode: always

    flyway:
      baseline-on-migrate: true

server:
  port: 8080
